CREATE TABLE IF NOT EXISTS `verizon`.`employee` (
  `eId` INT(11) NOT NULL AUTO_INCREMENT,
  `eName` VARCHAR(255) NULL DEFAULT NULL,
  `hireDate` DATETIME NULL DEFAULT NULL,
  `salary` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`eId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
